### ISSUE TITLE
Menü deplaziert wenn kein Language-Switcher widget angezeigt wird

### ISSUE THREAD

**Issue by cknoll** [bitsundbaeume/bits-und-baeume.org#25]
Mit Switcher (gut):

![image](https://user-images.githubusercontent.com/1315698/190017608-4806a27c-afa9-4e31-89fb-3643cfaa3a6b.png)

---

Ohne Switcher, z.B. unter <https://bits-und-baeume.org/konferenz-2022/material/>

→ verschoben:

![image](https://user-images.githubusercontent.com/1315698/190017715-415b02c4-2e7b-473f-bc1d-bf6b5cadce3d.png)

**Comment by michael-voit** [comment]
@cknoll Das ist nicht deplaziert, sondern die Elemente der drei Elemente (Logo, Menü, lanuage switcher), die angezeigt werden, werden als flex Elemente immer so weit voneinander entfernt verteilt auf die vorhandene Breite, wie möglich.

Welches Verhalten denkst Du sollte es haben? Das Logo und Menü gemeinsam mit Abstand x immer links ausgerichtet sind - und der language switcher stets rechts ausgerichtet, falls er vorhanden ist?

**Comment by cknoll** [comment]
@michael-voit Danke für die Hintergrundinfo. :+1: 

Ich würde erwarten, dass die Elemente, die immer da sind auch immer an der gleichen Stelle da sind. Der Language-Switcher ist imho das einzige Element, was manchmal da ist und manchmal nicht (wenn keine Übersetzung vorhanden ist). Im zweiten Fall sollte an seiner Stelle idealerweise ein leerer Platzhalter stehen, der genau so breit ist, wie es der Language-Switcher *wäre*.

Ich kann aber mit der aktuellen Situation gut leben und außer mir scheint es noch niemandem negativ aufgefallen zu sein. Solange sich das nicht ändert würde ich es erstmal so lassen.
