### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by cknoll** [bitsundbaeume/bits-und-baeume.org#62]
We got an email with the following report:

Status | URL | Source link text
-- | -- | --
404 Not Found | https://pretalx.c3voc.de/chaos-communication-camp-2023/cfp‌‌‌‌ | pretalx.c3voc.de/...
404 Not Found | https://discourse.bits-und-baeume.org/t/bits-baeume-treffen-in-luebeck/1607 | Bits &amp; Bäume Lübeck
404 Not Found | https://www.nachhaltige-digitalisierung.de/bits-baeume/forum-bits-baeume.html | Anmeldung und Infos
500 Internal Server Error | https://newsletter.bits-und-baeume.org/?p=subscribe&id=1 | Jetzt eintragen!
404 Not Found | https://cloud.bits-und-baeume.org/index.php/s/3CDZq6JFrQsqpH2?path=%2F | zu den Pressefotos
403  Forbidden | https://www.germanwatch.org/de/88048 | https://www.germanwatch.org/de/88048
404 Not Found | https://bits-und-baeume.org/community/forum/www.bits-und-baeume.org | Anmeldung und Infos
404 Not Found | https://bits-und-baeume.org/konferenz-2022/assets/images/2023/2023-04-17_Input-Papier_Gruenen  Fraktion.pdf | Input-Papier
404 Not Found | https://bits-und-baeume.org/en/conference-2022/about-us/ | EN
404 Not Found | https://bits-und-baeume.org/material/ | B&amp;B-Material
404 Not Found | https://bits-und-baeume.org/gallery/main/BuB-Forderungen_TK | +
404 Not Found | https://bits-und-baeume.org/gallery/main/BuB-Forderungen | +
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/bits-und-baeume-logo-konferenzinfos.pdf | Grafik mit Konferenzinfos
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/bits-und-baeume-logo-programmpunkte.pdf | Grafik mit Programmpunkten
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/bits-und-baeume-logo-traegerkreis.pdf | Grafik mit Trägerkreis
404 Not Found | https://bits-und-baeume.org/konferenz-2018/www.bits-und-baeume.org | Programmbeschreibung
404 Not Found | https://bits-und-baeume.org/en/konferenz-2018/demands/ | demands
404 Not Found | https://bits-und-baeume.org/conference-2022/join/ | here
404 Not Found | https://bits-und-baeume.org/en/community/forum/www.bits-und-baeume.org | Anmeldung und Infos
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/pressekit/bitsundbaeume22_Postkarte-1_DIN-A6_DRUCK_220805 | Postcard 1
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/pressekit/bitsundbaeume22_Postkarte-2_DIN-A6_DRUCK_220805 | Postcard 2
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/pressekit/bitsundbaeume22_Postkarte-3_DIN-A6_DRUCK_220805 | Postcard 3
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/pressekit/bitsundbaeume22_Postkarte-4_DIN-A6_DRUCK_220805 | Postcard 4
404 Not Found | https://bits-und-baeume.org/assets/images/oea_material/pressekit/bitsundbaeume22_Postkarte-5_DIN-A6_DRUCK_220805 | Postcard 5
404 Not Found | https://bits-und-baeume.org/konferenz-2022/mach-mit/ | DE
404 Not Found | https://bits-und-baeume.org/en/conference-2018/programme | program description
-1 Timeout | https://streaming.media.ccc.de/bub2022 | https://streaming.media.ccc.de/bub2022

**Comment by cknoll** [comment]
I am working on this, see https://codeberg.org/bits-und-baeume/bits-und-baeume.org/src/branch/ck-fix-dead-links

**Comment by cknoll** [comment]
https://newsletter.bits-und-baeume.org/ returns status code 500 (Internal Server Error)

the domain directs to `serpens.uberspace.de (95.143.172.177)`

This probably has to be fixed by @laryllian or @b3nks or whoever has access to that machine.

**Comment by cknoll** [comment]
most problems should be fixed in this preview:

https://bubdd.uber.space/stamm/vorschau/ck-fix-dead-links/

**Comment by bitsundbaeume** [comment]
some urls have been fixed. Will be checked again.

**Comment by bitsundbaeume** [comment]
Broken Link Check in internal Deck scheduled.
